name: Container Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_toolchain:
    name: Build Toolchain
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Container Image
        uses: docker/build-push-action@v6
        env:
          CONTAINER_REPO: ghcr.io/barrenechea/libxenon
        with:
          context: .
          file: libxenon.dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.CONTAINER_REPO }}:latest
          # platforms: linux/amd64,linux/arm64
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=min
